### ISSUE TITLE
How do I open URLs with CyanTrigger?

### ISSUE THREAD

**Issue by VertofChest** [CyanLaser/CyanTrigger#20]
Want to open a page to visit our app, nothing malicious.

**Comment by CyanLaser** [comment]
VRChat does not provide a way for general creators to open webpages, and thus CyanTrigger does not have this functionality. The only worlds within VRChat that have the privilege to open webpages are sponsored worlds, such as VKet, which require permission from VRChat directly. 

If instead you only wanted to ping a web server without opening a browser on the players computer, then vrchat provides VRCUrl options for video players, image downloader, and string downloader, which all work with CyanTrigger.

**Comment by VertofChest** [comment]
> VRChat does not provide a way for general creators to open webpages, and thus CyanTrigger does not have this functionality. The only worlds within VRChat that have the privilege to open webpages are sponsored worlds, such as VKet, which require permission from VRChat directly.
> 
> If instead you only wanted to ping a web server without opening a browser on the players computer, then vrchat provides VRCUrl options for video players, image downloader, and string downloader, which all work with CyanTrigger.

Alright, thanks. I'd like to use the image downloader. Unfortunately since CyanTrigger is not open-sourced I can't go through the code and see exactly where this is. Would you be offering to tell me just how to set that up?

My usages required are simple: Load an image from a website and display it on a bulletin board. Thanks for the speedy reply!

**Comment by CyanLaser** [comment]
The best place to start learning about a VRChat provided feature would be the vrchat documentation. Here is the link on loading images: https://docs.vrchat.com/docs/image-loading

While this mainly explains it for UdonGraph, it works very similar for CyanTrigger. To add the specific actions, press the plus button, search for the type you want, in this case it is "VRCImageDownloader", and then select the action you want. See the image for a recreation of VRChat's UdonGraph example rebuilt in CyanTrigger. You can also just use the UdonGraph version directly instead of remaking it. VRChat's own example scenes show how to use the UdonGraph program. This CyanTrigger program will be included in the next version, when that is ready to be released.

As a side note, since image downloading is provided by VRChat, the CyanTrigger source code has no mentions of this and would not have been helpful. CyanTrigger is just a UI and compiler for Udon similar to UdonGraph and U#, but all functionality is provided through the VRChat sdk. 

<img width="452" alt="image" src="https://user-images.githubusercontent.com/50863419/235802269-e4cc4b1a-0450-4c2f-a58f-4e6bcd3cbc47.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/50863419/235802475-556cded6-ea0e-49c1-a915-b1766929261a.png">
